# Generated by Django 3.1.2 on 2020-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='museum',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='museum',
            name='website',
            field=models.URLField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='museum',
            name='img',
            field=models.CharField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='museum',
            name='introduce',
            field=models.CharField(default=None, max_length=1500),
        ),
    ]
