# Generated by Django 3.1.2 on 2020-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201120_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='mname',
            field=models.CharField(max_length=50),
        ),
    ]
