# Generated by Django 3.1.2 on 2020-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201120_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
