# Generated by Django 3.1.2 on 2020-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201120_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='mname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
