# Generated by Django 3.1.2 on 2020-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201120_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='introduce',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
    ]
