# Generated by Django 3.1.2 on 2020-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201120_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='address',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='museum',
            name='mname',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
