# Generated by Django 3.1.2 on 2020-11-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201120_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='mname',
            field=models.CharField(max_length=500),
        ),
    ]
