# Generated by Django 3.1.2 on 2020-12-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_comment'),
        ('main', '0014_auto_20201120_2351'),
    ]

    operations = [
    ]
