# Generated by Django 3.0.3 on 2020-11-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-commenttime',)},
        ),
    ]
