# Generated by Django 3.0.3 on 2020-11-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20201128_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('commenttime',)},
        ),
    ]
